-- DB_ORGANIZER0528 USER

CREATE DATABASE DB_ORGANIZER0528;
USE DB_ORGANIZER0528;


-- MEMBER TABLE 

CREATE TABLE TBL_MEMBER(
	M_NO INT AUTO_INCREMENT UNIQUE,
    M_ID VARCHAR(30) NOT NULL UNIQUE,
    M_PW VARCHAR(100) NOT NULL,
    M_MAIL VARCHAR(50) NOT NULL,
    M_PHONE VARCHAR(30) NOT NULL,
    M_REG_DATE DATETIME DEFAULT NOW(),
    M_MOD_DATE DATETIME DEFAULT NOW(), 
    PRIMARY KEY(M_ID)
);

ALTER TABLE TBL_MEMBER 
ADD COLUMN M_ROLE VARCHAR(20) DEFAULT 'USER_PENDING' AFTER M_PHONE;

SELECT * FROM TBL_MEMBER;
DELETE FROM TBL_MEMBER;


